# ||--------------------------------------------------------------------------------||
# ||                                Plex Applications                               ||
# ||--------------------------------------------------------------------------------||
version: "3.6"

services:
  notifiarr:
    image: golift/notifiarr
    container_name: notifiarr
    environment:
      - PGID=100
      - PUID=1024
      - TZ=America/Chicago
      - UMASK=002
    networks:
      - media
    volumes:
      - /var/run/utmp:/var/run/utmp
      - /volume1/docker/notifiarr/notifiarr.conf:/config/notifiarr.conf
    ports:
      - 5454:5454
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PGID=100
      - PUID=1024
      - TZ=America/Chicago
      - UMASK=002
    networks:
      - media
    volumes:
      - /volume1/docker/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PGID=100
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PLEX_PASS=yes
      - PUID=1024
      - UMASK=002
      - VERSION=docker
    networks:
      - media
    volumes:
      - /volume1/Books:/books
      - /volume1/docker/plex/config:/config
      - /volume1/Movies:/movies
      - /volume1/Music:/music
      - /volume1/TV:/tv
    ports:
      - 3005:3005
      - 32400:32400
      - 32410:32410
      - 32412:32412
      - 32413:32413
      - 32414:32414
      - 32469:32469
      - 8324:8324
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PGID=100
      - PUID=1024
      - TZ=America/Chicago
      - UMASK=002
    networks:
      - media
    volumes:
      - /volume1/docker/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped

networks:
  media:
    name: media
    external: true
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"
      com.docker.network.bridge.name: "media"
      com.docker.network.driver.mtu: "1500"
    ipam:
      config:
        - subnet: ${SUBNET}
          gateway: ${GATEWAY_IP}
          ip_range: ${IP_RANGE}
