# ||--------------------------------------------------------------------------------||
# ||                                Plex Applications                               ||
# ||--------------------------------------------------------------------------------||
version: "3.9"

services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    hostname: emby
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    volumes:
      - ${CONFIG_BASE_DIR}/emby:/config
      - ${MOVIES_DIR_LOCAL}:${MOVIES_DIR_RELATIVE}
      - ${TV_DIR_LOCAL}:${TV_DIR_RELATIVE}
    ports:
      - 8097:8096
      - 8921:8920
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    networks:
      - media
    volumes:
      - ${BOOKS_DIR_LOCAL}:${BOOKS_DIR_RELATIVE}
      - ${CONFIG_BASE_DIR}/jellyfin:/config
      - ${MOVIES_DIR_LOCAL}:${MOVIES_DIR_RELATIVE}
      - ${MUSIC_DIR_LOCAL}:${MUSIC_DIR_RELATIVE}
      - ${TV_DIR_LOCAL}:${TV_DIR_RELATIVE}
    ports:
      # - 1900:1900/udp
      - 7359:7359/udp
      - 8096:8096
      - 8920:8920
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    hostname: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    networks:
      - media
    volumes:
      - ${CONFIG_BASE_DIR}/jellyseerr:/app/config
    ports:
      - 5056:5055
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    hostname: overseerr
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    networks:
      - media
    volumes:
      - ${CONFIG_BASE_DIR}/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    hostname: plex
    environment:
      - PGID=${PGID}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PLEX_PASS=yes
      - PUID=${PUID}
      - UMASK=${UMASK}
      - VERSION=docker
    networks:
      - media
    volumes:
      - ${BOOKS_DIR_LOCAL}:${BOOKS_DIR_RELATIVE}
      - ${CONFIG_BASE_DIR}/plex/config:/config
      - ${MOVIES_DIR_LOCAL}:${MOVIES_DIR_RELATIVE}
      - ${MUSIC_DIR_LOCAL}:${MUSIC_DIR_RELATIVE}
      - ${PERSONAL_DIR_LOCAL}:${PERSONAL_DIR_RELATIVE}
      - ${TV_DIR_LOCAL}:${TV_DIR_RELATIVE}
    ports:
      - 3005:3005
      - 8324:8324
      - 32400:32400
      - 32410:32410
      - 32412:32412
      - 32413:32413
      - 32414:32414
      - 32469:32469
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    hostname: tautulli
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    networks:
      - media
    volumes:
      - ${CONFIG_BASE_DIR}/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped

networks:
  media:
    name: media
    external: true
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"
      com.docker.network.bridge.name: "media"
      com.docker.network.driver.mtu: "1500"
    ipam:
      config:
        - subnet: ${SUBNET}
          gateway: ${GATEWAY_IP}
          ip_range: ${IP_RANGE}
