# ||--------------------------------------------------------------------------------||
# ||                              Crypto Applications                               ||
# ||--------------------------------------------------------------------------------||

version: "3.9"

services:
  rana:
    image: rana:latest
    container_name: rana
    hostname: rana
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    networks:
      - media
    entrypoint: "/app/target/release/rana"
    command: ${RANA_ARGUMENTS} # -n=j0hnwyles,j0hnwyl3s -c 4
    restart: "no"

  vanity-age:
    image: vanity-age:latest
    container_name: vanity-age
    hostname: vanity-age
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    networks:
      - media
    entrypoint: /app/vanity-age
    command: '${VANITY_AGE_ARGUMENTS}' # '\d+j0hn\d?wyles.*'
    restart: "no"

networks:
  media:
    name: media
    external: true
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"
      com.docker.network.bridge.name: "media"
      com.docker.network.driver.mtu: "1500"
    ipam:
      config:
        - subnet: ${SUBNET}
          gateway: ${GATEWAY_IP}
          ip_range: ${IP_RANGE}
