# ||--------------------------------------------------------------------------------||
# ||                               Other Applications                               ||
# ||--------------------------------------------------------------------------------||

# TODO: ALL files should have "depends_on"

version: "3.6"

services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    hostname: searxng
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    networks:
      - media
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
    volumes:
      - ${CONFIG_BASE_DIR}/searxng:/etc/searxng:rw
    ports:
      - 8082:8080

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    networks:
      - media
    volumes:
      - ${CONFIG_DATA_DIR}:/downloads
      - ${CONFIG_BASE_DIR}/syncthing:/config
      - /volume1/Documents/sync:/sync
    ports:
      - 21027:21027/udp
      - 22000:22000/tcp
      - 22000:22000/udp
      - 8384:8384
    restart: unless-stopped

  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: extropy-nas-tailscale
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    privileged: true
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TAILSCALE_HOSTNAME=${TAILSCALE_HOSTNAME:?err}
      - TAILSCALE_STATE_ARG=${TAILSCALE_STATE_ARG}
      - TS_AUTH_KEY=${TS_AUTH_KEY:?err}
      - TZ=${TZ}
      - UMASK=${UMASK}
      # TODO: Add these
      # TS_AUTH_KEY: a Tailscale auth key, i.e. what you'd pass to tailscale --authkey=
      # TS_KUBE_SECRET: if running in Kubernetes, secret name where to store Tailscale state
      # TS_DEST_IP: destination IP, if deploying Tailscale as a proxy
      # TS_ROUTES: tailscale --advertise-routes=
      # TS_ACCEPT_DNS: tailscale --accept-dns=
      # TS_SOCKET: tailscale --socket=
      # TS_EXTRA_ARGS: any other CLI flags for tailscale
      # TS_USERSPACE: tailscaled --tun=userspace-networking
      # TS_STATE_DIR: tailscaled --statedir=
      # TS_SOCKS5_SERVER: set to an addr+port for the SOCKS5 proxy like :1055, which will be passed to tailscaled --socks5-server=:1055
      # TS_OUTBOUND_HTTP_PROXY_LISTEN: set to an addr+port for the HTTP proxy like :1055, which will be passed to tailscaled --outbound-http-proxy-listen=:1055
      # TS_TAILSCALED_EXTRA_ARGS: any other flags for tailscaled
    network_mode: host
    volumes:
      - ${CONFIG_BASE_DIR}/tailscale:/var/lib
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    hostname: watchtower
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - UMASK=${UMASK}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_NOTIFICATION_REPORT=true
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_NOTIFICATION_URL}
      - WATCHTOWER_POLL_INTERVAL=21600
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - media
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

networks:
  media:
    name: media
    # external: true
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"
      com.docker.network.bridge.name: "media"
      com.docker.network.driver.mtu: "1500"
    ipam:
      config:
        - subnet: ${SUBNET}
          gateway: ${GATEWAY_IP}
          ip_range: ${IP_RANGE}
