# ||--------------------------------------------------------------------------------||
# ||                              StarArr Applications                              ||
# ||--------------------------------------------------------------------------------||
version: "3.9"

services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    hostname: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    networks:
      - media
    volumes:
      - ${CONFIG_BASE_DIR}/bazarr:/config
      - ${MOVIES_DIR_LOCAL}:${MOVIES_DIR_RELATIVE}
      - ${TV_DIR_LOCAL}:${TV_DIR_RELATIVE}
    ports:
      - 6767:6767
    restart: unless-stopped

  bazarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0
    container_name: bazarr-exporter
    hostname: bazarr-exporter
    command: ["bazarr"]
    environment:
      PORT: 9712
      URL: http://bazarr:6767
      APIKEY: ${BAZARR_API_KEY}
    networks:
      - media
    ports:
      - 9712:9712
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    hostname: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    networks:
      - media
    ports:
      - 8686:8686
    volumes:
      - ${CONFIG_BASE_DIR}/lidarr:/config
      - ${MUSIC_DIR_LOCAL}:${MUSIC_DIR_RELATIVE}
      - ${DOWNLOADS_DIR_COMPLETE_LOCAL}:${DOWNLOADS_DIR_COMPLETE_RELATIVE}
      - ${DOWNLOADS_DIR_INCOMPLETE_LOCAL}:${DOWNLOADS_DIR_INCOMPLETE_RELATIVE}
    restart: unless-stopped

  lidarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0
    container_name: lidarr-exporter
    hostname: lidarr-exporter
    environment:
      PORT: 9709
      URL: http://lidarr:8686
      APIKEY: ${LIDARR_API_KEY}
    networks:
      - media
    ports:
      - 9709:9709
    command: ["lidarr"]
    restart: unless-stopped

  mylar3:
    image: lscr.io/linuxserver/mylar3:latest
    container_name: mylar3
    hostname: mylar3
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    networks:
      - media
    volumes:
      - ${CONFIG_BASE_DIR}/mylar3:/config
      - ${COMICS_DIR_LOCAL}:${COMICS_DIR_RELATIVE}
      - ${DOWNLOADS_DIR_COMPLETE_LOCAL}:${DOWNLOADS_DIR_COMPLETE_RELATIVE}
      - ${DOWNLOADS_DIR_INCOMPLETE_LOCAL}:${DOWNLOADS_DIR_INCOMPLETE_RELATIVE}
    ports:
      - 8090:8090
    restart: unless-stopped

  notifiarr:
    image: golift/notifiarr
    container_name: notifiarr
    hostname: notifiarr
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    networks:
      - media
    volumes:
      - /var/run/utmp:/var/run/utmp
      - ${CONFIG_BASE_DIR}/notifiarr:/config
    ports:
      - 5454:5454
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    networks:
      - media
    volumes:
      - ${CONFIG_BASE_DIR}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  prowlarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0
    container_name: prowlarr-exporter
    hostname: prowlarr-exporter
    environment:
      PORT: 9710
      URL: http://prowlarr:8080
      APIKEY: ${PROWLARR_API_KEY}
      # PROWLARR_BACKFILL: true # optional
      # PROWLARR_BACKFILL_SINCE_DATE: "2023-03-01" # optional
    networks:
      - media
    ports:
     - 9710:9710
    command: ["prowlarr"]
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    networks:
      - media
    volumes:
      - ${MOVIES_DIR_LOCAL}:${MOVIES_DIR_RELATIVE}
      - ${CONFIG_BASE_DIR}/radarr:/config
      - ${DOWNLOADS_DIR_COMPLETE_LOCAL}:${DOWNLOADS_DIR_COMPLETE_RELATIVE}
      - ${DOWNLOADS_DIR_INCOMPLETE_LOCAL}:${DOWNLOADS_DIR_INCOMPLETE_RELATIVE}
    ports:
      - 7878:7878
    restart: unless-stopped

  radarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0
    container_name: radarr-exporter
    hostname: radarr-exporter
    environment:
      PORT: 9708
      URL: http://radarr:7878
      APIKEY: ${RADARR_API_KEY}
    networks:
      - media
    ports:
      - 9708:9708
    command: ["radarr"]
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    hostname: readarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    networks:
      - media
    volumes:
      - ${BOOKS_DIR_LOCAL}:${BOOKS_DIR_RELATIVE}
      - ${CONFIG_BASE_DIR}/readarr:/config
      - ${DOWNLOADS_DIR_COMPLETE_LOCAL}:${DOWNLOADS_DIR_COMPLETE_RELATIVE}
      - ${DOWNLOADS_DIR_INCOMPLETE_LOCAL}:${DOWNLOADS_DIR_INCOMPLETE_RELATIVE}
    ports:
      - 8787:8787
    restart: unless-stopped

  readarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0
    container_name: readarr-exporter
    hostname: readarr-exporter
    environment:
      PORT: 9713
      URL: http://readarr:8787
      APIKEY: ${READARR_API_KEY}
    networks:
      - media
    ports:
      - 9713:9713
    command: ["readarr"]
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    networks:
      - media
    volumes:
      - ${TV_DIR_LOCAL}:${TV_DIR_RELATIVE}
      - ${CONFIG_BASE_DIR}/sonarr:/config
      - ${DOWNLOADS_DIR_COMPLETE_LOCAL}:${DOWNLOADS_DIR_COMPLETE_RELATIVE}
      - ${DOWNLOADS_DIR_INCOMPLETE_LOCAL}:${DOWNLOADS_DIR_INCOMPLETE_RELATIVE}
    ports:
      - 8989:8989
    restart: unless-stopped

  sonarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0
    container_name: sonarr-exporter
    hostname: sonarr-exporter
    environment:
      PORT: 9707
      URL: http://sonarr:8989
      APIKEY: ${SONARR_API_KEY}
    networks:
      - media
    ports:
      - 9707:9707
    command: ["sonarr"]
    restart: unless-stopped

networks:
  media:
    name: media
    external: true
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"
      com.docker.network.bridge.name: "media"
      com.docker.network.driver.mtu: "1500"
    ipam:
      config:
        - subnet: ${SUBNET}
          gateway: ${GATEWAY_IP}
          ip_range: ${IP_RANGE}
