global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "bazarr-exporter"
    static_configs:
      - targets: ["bazarr-exporter:9712"]

  - job_name: "lidarr-exporter"
    static_configs:
      - targets: ["lidarr-exporter:9711"]

  - job_name: "prowlarr-exporter"
    static_configs:
      - targets: ["prowlarr-exporter:9709"]

  - job_name: "radarr-exporter"
    static_configs:
      - targets: ["radarr-exporter:9708"]

  - job_name: "sabnzbd-exporter"
    static_configs:
      - targets: ["sabnzbd-exporter:9710"]

  - job_name: "sonarr-exporter"
    static_configs:
      - targets: ["sonarr-exporter:9707"]
