{
 "title": "Synology DashBoard",
 "description": "A Dashboard to monitor Synology NAS",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "InfluxDB", "query": "influxdb" },
   {
    "name": "host",
    "label": "Syno:",
    "query": "SHOW TAG VALUES FROM \"snmp.SYNO\" WITH KEY = \"agent_host\""
   },
   {
    "name": "intf",
    "label": "Interface:",
    "query": "SHOW TAG VALUES FROM \"ifTable\" WITH KEY = \"ifDescr\" WHERE \"agent_host\" =~ /^$host/"
   },
   {
    "name": "appname",
    "label": "Appname",
    "query": "SHOW TAG VALUES FROM syslog WITH KEY=appname"
   },
   {
    "name": "logHost",
    "label": "LogHostname",
    "query": "SHOW TAG VALUES FROM syslog WITH KEY=hostname"
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": "SHOW TAG VALUES FROM syslog WITH KEY=severity"
   },
   {
    "name": "disk",
    "label": "disk",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"name\""
   },
   { "name": "Query", "label": "LogQuery" },
   { "name": "inter", "label": "Interval", "query": "1m" }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Synology NAS",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "$col",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "measurement": "snmp.SYNO",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "modelName" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Synology Model" ], "type": "alias" }
      ],
      [
       { "params": [ "version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "DSM Version" ], "type": "alias" }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_diskID",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "diskID" ], "type": "tag" }
     ],
     "measurement": "diskTable",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"diskStatus\") FROM \"diskTable\" WHERE (\"agent_host\" =~ /^$host$/) AND $timeFilter GROUP BY \"diskID\"",
     "select": [
      [
       { "params": [ "diskStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_diskID",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "diskID" ], "type": "tag" }
     ],
     "measurement": "diskTable",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "diskTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "NAS Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Connected Users/Servicess",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$col",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "measurement": "snmp.SYNO",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"usersSSH\") AS \"SSH\", last(\"usersHTTP\") AS \"HTTP\", last(\"usersSFTP\") AS \"SFTP\" FROM \"snmp.SYNO\" WHERE (\"agent_host\" = '192.168.86.149') AND $timeFilter",
     "select": [
      [
       { "params": [ "usersSSH" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "SSH" ], "type": "alias" }
      ],
      [
       { "params": [ "usersHTTP" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "HTTP" ], "type": "alias" }
      ],
      [
       { "params": [ "usersSFTP" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "SFTP" ], "type": "alias" }
      ],
      [
       { "params": [ "usersCIFS" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "CIFS" ], "type": "alias" }
      ],
      [
       { "params": [ "usersAFP" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "AFP" ], "type": "alias" }
      ],
      [
       { "params": [ "usersNFS" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "NFS" ], "type": "alias" }
      ],
      [
       { "params": [ "usersFTP" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "FTP" ], "type": "alias" }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "snmp.SYNO",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Ram ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Raid Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$col",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "raidName" ], "type": "tag" }
     ],
     "measurement": "raidTable",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "raidStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Overall status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "sysName" ], "type": "tag" }
     ],
     "measurement": "snmp.SYNO",
     "select": [
      [
       { "params": [ "systemStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "agent_host" ], "type": "tag" }
     ],
     "measurement": "snmp.SYNO",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "powerStatus" ], "type": "field" }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Upgrade Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "agent_host" ], "type": "tag" }
     ],
     "measurement": "snmp.SYNO",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "upgradeAvailable" ], "type": "field" }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Fan status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "measurement": "snmp.SYNO",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "systemFanStatus" ], "type": "field" }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Disk Write iops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$tag_name: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "io_reads",
     "query": "SELECT non_negative_derivative(mean(writes),1s) as \"write\" FROM \"diskio\" WHERE \"name\" =~ /md[2-3]$/AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Read I/O time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_name: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "io_reads",
     "query": "SELECT non_negative_derivative(mean(read_time),1s) as \"read\" FROM \"diskio\" WHERE  \"name\" =~ /md[2-3]$/ AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Write I/O time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_name: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "io_reads",
     "query": "SELECT non_negative_derivative(mean(write_time),1s) as \"write\" FROM \"diskio\" WHERE \"name\" =~ /md[2-3]$/ AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Read iops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$tag_name: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "io_reads",
     "query": "SELECT non_negative_derivative(mean(reads),1s) as \"write\" FROM \"diskio\" WHERE \"name\" =~ /md[2-3]$/AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Write Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "SHR Array (Volume 1)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(\"write_bytes\"), 1s) FROM \"diskio\" WHERE (\"host\" = '0d42d827caee' AND \"name\" = 'md2') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "md2" }
     ]
    },
    {
     "alias": "SSD Disk (Volume 2)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "md3" }
     ]
    }
   ]
  },
  {
   "title": "Disk Read Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "SHR Array (Volume 1)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(\"read_bytes\"), 1s) FROM \"diskio\" WHERE (\"host\" = '0d42d827caee' AND \"name\" = 'md2') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "md2" }
     ]
    },
    {
     "alias": "SSD Disk (Volume 2)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "md3" }
     ]
    }
   ]
  },
  {
   "title": "Disk Model & Status",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "diskID" ], "type": "tag" }
     ],
     "measurement": "diskTable",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "diskModel" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Model" ], "type": "alias" }
      ],
      [
       { "params": [ "diskStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Status" ], "type": "alias" }
      ],
      [
       { "params": [ "diskType" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Disk Type" ], "type": "alias" }
      ],
      [
       { "params": [ "diskTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "CurrentC" ], "type": "alias" }
      ],
      [
       { "params": [ "diskTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "MaxC" ], "type": "alias" }
      ],
      [
       { "params": [ "diskTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "MinC" ], "type": "alias" }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "CPU/RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "System" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "User" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "I/O" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "cpu_percentageBusy",
     "query": "SELECT mean(running) as running, mean(blocked) as blocked, mean(sleeping) as sleeping, mean(stopped) as stopped, mean(zombies) as zombies, mean(paging) as paging, mean(unknown) as unknown FROM \"processes\" WHERE  $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "system_load1",
     "query": "SELECT mean(load1) as load1,mean(load5) as load5,mean(load15) as load15 FROM \"system\" WHERE  $timeFilter GROUP BY time($interval), * ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU usage per core",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_cpu",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "cpu_percentageBusy",
     "query": "SELECT 100 - mean(\"usage_idle\") FROM \"cpu\" WHERE (\"cpu\" =~ /cpu[0-9].*/) AND $timeFilter GROUP BY time($interval), \"cpu\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Used (%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Memory Used %",
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Network:$col",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifTable",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "ifInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "in" ], "type": "alias" }
      ],
      [
       { "params": [ "ifOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "out" ], "type": "alias" }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Syslog Messages",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "appname" ], "type": "tag" }
     ],
     "measurement": "syslog",
     "select": [
      [
       { "params": [ "severity_code" ], "type": "field" }
      ],
      [
       { "params": [ "message" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$logHost$/" },
      { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" },
      { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" },
      { "condition": "AND", "key": "message", "operator": "=~", "value": "/$Query/" }
     ]
    }
   ]
  },
  {
   "title": "syslog count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "none", "label": "Messages / min" }
   ],
   "targets": [
    {
     "alias": "Info",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "syslog",
     "select": [
      [
       { "params": [ "severity_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "severity", "operator": "=", "value": "info" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$logHost$/" },
      { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" },
      { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" },
      { "condition": "AND", "key": "message", "operator": "=~", "value": "/$Query/" }
     ]
    },
    {
     "alias": "Notice",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "syslog",
     "select": [
      [
       { "params": [ "severity_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "severity", "operator": "=", "value": "notice" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$logHost$/" },
      { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" },
      { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" },
      { "condition": "AND", "key": "message", "operator": "=~", "value": "/$Query/" }
     ]
    },
    {
     "alias": "Warning",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "syslog",
     "select": [
      [
       { "params": [ "severity_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "severity", "operator": "=", "value": "warning" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$logHost$/" },
      { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" },
      { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" },
      { "condition": "AND", "key": "message", "operator": "=~", "value": "/$Query/" }
     ]
    },
    {
     "alias": "Error",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "syslog",
     "select": [
      [
       { "params": [ "severity_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "severity", "operator": "=", "value": "err" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$logHost$/" },
      { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" },
      { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" },
      { "condition": "AND", "key": "message", "operator": "=~", "value": "/$Query/" }
     ]
    },
    {
     "alias": "Critical",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "syslog",
     "select": [
      [
       { "params": [ "severity_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "severity", "operator": "=", "value": "crit" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$logHost$/" },
      { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" },
      { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" },
      { "condition": "AND", "key": "message", "operator": "=~", "value": "/$Query/" }
     ]
    },
    {
     "alias": "Alert",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "syslog",
     "select": [
      [
       { "params": [ "severity_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "severity", "operator": "=", "value": "alert" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$logHost$/" },
      { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" },
      { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" },
      { "condition": "AND", "key": "message", "operator": "=~", "value": "/$Query/" }
     ]
    },
    {
     "alias": "Emergency",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "syslog",
     "select": [
      [
       { "params": [ "severity_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "severity", "operator": "=", "value": "emerg" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$logHost$/" },
      { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" },
      { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" },
      { "condition": "AND", "key": "message", "operator": "=~", "value": "/$Query/" }
     ]
    }
   ]
  }
 ]
}